### ISSUE TITLE
allow pdf exports

### ISSUE THREAD

**Issue by Dan33l** [LINCnil/pia-app#4]
an export in pdf allows to show PIA out of the dedicated software

**Comment by LaboCNIL** [comment]
Hi,

It is possible to export the pia report in pdf using the print feature.

**Comment by Dan33l** [comment]
It looks a workaround. It does not provide nice display and generated graphics.

**Comment by jgachelin** [comment]
I'm also interested to have this functionality native into the software, in order not to use third party software like PDF Creator. Thanks :)

**Comment by brunto** [comment]
This feature might be implemented soon.

**Comment by kevin-atnos** [comment]
This is possible since release 2.1.0 (June 2019) :
https://github.com/LINCnil/pia-app/releases/tag/2.1.0

You can't directly have a .pdf from your PIA but you can export your PIA as a .doc.
You can also export all graphics from your PIA.
Then it's easy to transform all of this in a .pdf document.

The next version (2.2.0) coming out very soon will enhance the export system (including images, .csv, .doc, attachments, ... in .zip folders).
